development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://xbzbvcxjcaknlq:e2cf543dd9d26fd654035447c8ff2256f1636fc821259a29c18891310e0fda7b@ec2-54-243-216-33.compute-1.amazonaws.com:5432/d63j1thd1kiure
  channel_prefix: nameofapp_production
